<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<PackageId>AlgoTemp</PackageId>
	<Version>1.0.0</Version>
	<Authors>Algo</Authors>
	<Company>Algo</Company>
	<Description>A sample .NET library for NuGet publishing</Description>
	<PackageTags>dotnet library nuget</PackageTags>
	<RepositoryUrl>https://github.com/00009294/AlgoTemp</RepositoryUrl>
	<PackageLicenseExpression>MIT</PackageLicenseExpression>
	<PackageProjectUrl>https://github.com/00009294/AlgoTemp</PackageProjectUrl>

  </PropertyGroup>

</Project>
